require "./lib/player"
require "./spec/helpers/scenario"
require "json"

RSpec.describe Player do
  describe "::move" do
    let(:health) { 51 }

    let(:data) do
      Scenario.generate(<<~TXT, health: {"A" => health})
        ...........
        ...........
        ...........
        ...........
        ..*........
        .....*.....
        .....B.....
        .....bb....
        ......b....
        Aaa........
        .....*.....
      TXT
    end

    subject { Player.move(data) }

    it { is_expected.to eq("up") }

    describe "with low health" do
      let(:health) { 50 }

      it { is_expected.to eq("down") }
    end
  end
end
